### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ELLON007** [xiaopin/NavigationContainer#11]
使用popToViewController的时候崩溃
Assertion failure in -[XPRootNavigationController popToViewController:transition:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.140/UINavigationController.m:8176
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Tried to pop to a view controller that doesn't exist.'
terminating with uncaught exception of type NSException
2021-10-15 13:50:24.162839+0800 Example[8982:2684118] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Tried to pop to a view controller that doesn't exist.'
*** First throw call stack:
(0x182bab180 0x181d839f8 0x182ac488c 0x183588b38 0x1aef506b4 0x1aef503cc 0x10059547c 0x100591f38 0x100634c78 0x100637ffc 0x10064a610 0x10064256c 0x182b3cb20 0x182b37a58 0x182b36fb4 0x184d3879c 0x1af582c38 0x100593c94 0x1825fa8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by xiaopin** [comment]
可否给点代码看看

**Comment by ELLON007** [comment]
我就是在你的demo中创建了三个控制器，然后vc3 popToViewController vc1 然后就崩溃了，，用了你这个框架很久了，一直就有这个问题

**Comment by xiaopin** [comment]
这样的话，你直接把demo打包发我邮箱吧 pincheng23@hotmail.com

**Comment by ELLON007** [comment]
发过去了

**Comment by xiaopin** [comment]
@ELLON007 已经修复了，你下载最新代码试试，感谢反馈！

**Comment by ELLON007** [comment]
👍🏻
