### ISSUE TITLE
在控制器中修改viewcontrollers数组,方法不跳转

### ISSUE THREAD

**Issue by liuhuan9337** [xiaopin/NavigationContainer#7]
增加拦截方法后,tabController会显示出来

**Comment by xiaopin** [comment]
请问你拦截了哪个方法，是否可以把你的代码展示一下，如果可以，提供一个demo是最好的

**Comment by liuhuan9337** [comment]
不是在一级界面下方的tabBarController确出来了,每次运行的都会出现这个问题,我修改的是第三级界面
| |
刘欢
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年08月17日 ***@***.***> 写道：

请问你拦截了哪个方法，是否可以把你的代码展示一下，如果可以，提供一个demo是最好的

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
