### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by liuhuan9337** [xiaopin/NavigationContainer#9]
在.m文件中增加了方法
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSArray *actions = @[
                             NSStringFromSelector(@selector(pushViewController:animated:)),
                             NSStringFromSelector(@selector(popViewControllerAnimated:)),
                             NSStringFromSelector(@selector(popToViewController:animated:)),
                             NSStringFromSelector(@selector(popToRootViewControllerAnimated:)),
                             NSStringFromSelector(@selector(viewControllers)),
                             NSStringFromSelector(@selector(tabBarController)),
                             NSStringFromSelector(@selector(setViewControllers:))
//                             NSStringFromSelector(@selector(setViewControllers:animated:))
                             ];
        
        for (NSString *str in actions) {
            xp_swizzled(self, NSSelectorFromString(str), NSSelectorFromString([@"xp_" stringByAppendingString:str]));
        }
    });
}

- (void)xp_setViewControllers:(NSArray<__kindof UIViewController *> *)viewControllers {
    XPRootNavigationController *rootNavigationController = [self rootNavigationController];
    if (rootNavigationController) {
        return [rootNavigationController setViewControllers:viewControllers];
    }
    [self xp_setViewControllers:viewControllers];
}

在推出第三个界面时.删除中间的那个界面,然后tabBarController就会出现      
  NSMutableArray *viewControllerArrays = [NSMutableArray array];
        [viewControllerArrays addObject:self.navigationController.viewControllers.firstObject];
        [viewControllerArrays addObject:self.navigationController.viewControllers.lastObject];
        [self.navigationController setViewControllers:viewControllerArrays];

**Comment by xiaopin** [comment]
针对 TabBar 的问题，你直接修改下源码吧，找到 `XPRootNavigationController` 这个类，然后按下面修改
```ObjC
- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated {
    viewController.hidesBottomBarWhenPushed = YES; // 添加这行代码
    // 之前的代码....
}
```
我在我的项目中，是在 pch 文件中添加了 `kXPNavigationControllerClassName` 宏来设置默认导航栏，默认导航栏中将 `hidesBottomBarWhenPushed` 设为了 `YES`。
还有，我不知道你基于什么原因要通过修改  `viewControllers` 数组来改变当前控制器，我没这么用过，所以对这个用法不太兼容。你有兴趣的话，你可以自己修改下源码来适配。
